#pragma once

#include "NativeGameplayTags.h"

namespace GAFGamePlayTags
{
	// 步态
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gait_Walk);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gait_Run);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gait_Sprint);
	
	// 站姿
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stance_Stand);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stance_Crouch);
	
	// 输入
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_WorldSpace);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Gamepad);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeRotationMode);
} // namespace GAFGamePlayTags