#pragma once

#include "NativeGameplayTags.h"

namespace GAFGamePlayTags
{
	// 输入
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move_WorldSpace);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Gamepad);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeRotationMode);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeCameraSide);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ChangeCameraDistance);

	// 步态
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gait);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gait_Walk);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gait_Run);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gait_Sprint);

	// 站姿
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stance);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stance_Stand);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stance_Crouch);

	// MovementMode
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_OnGround);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_InAir);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Sliding);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementMode_Traversing);

	// MovementState
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementState);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementState_Idle);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementState_Moving);

	// RotationMode
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RotationMode);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RotationMode_OrientToMovement);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RotationMode_Strafe);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RotationMode_Aim);

	// InputState
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState_WantsToSprint);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState_WantsToWalk);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState_WantsToStrafe);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState_WantsToAim);
	GAF_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputState_WantsToCrouch);
} // namespace GAFGamePlayTags
